version: 2

models:
  - name: dim_region
    columns:
      - name: region_id
        tests:
          - unique
          - not_null
      - name: region_code
        tests:
          - unique
          - not_null
      - name: region_name
        tests:
          - not_null

  - name: dim_time
    columns:
      - name: time_id
        tests:
          - unique
          - not_null
      - name: year
        tests:
          - unique
          - not_null

  - name: fact_population
    columns:
      - name: region_id
        tests:
          - not_null
      - name: time_id
        tests:
          - not_null
      - name: population
        tests:
          - not_null